#page title
page_title                                : FlashWise                                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6469705776                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/Icon-1024.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : FlashWise redefines learning with its Quick Search feature, enabling instant access to terms and their automatic incorporation into flashcards. Say goodbye to tedious manual data entry. Enhance your study experience and efficiency with FlashWise's intelligent flashcard automation and rapid search capabilities.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Fatima Kahbi                               
your_link                                 :                     
your_city                                 :                                 
email_address                             : fatimabk.dev@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : fatimabk1
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Automatic Definitions and Examples
    description                           : Instantly populate flashcards with accurate term definitions and relevant examples, saving time and ensuring accurate content.
    fontawesome_icon_name                 : magic
    
  - title                                 : Quick Search
    description                           : Easily search and add terms to decks, improving study efficiency.
    fontawesome_icon_name                 : mobile

  - title                                 : Efortless Deck Management
    description                           : Swipe to edit and delete decks, keeping study materials organized.
    fontawesome_icon_name                 : play-circle

  - title                                 : Progress Indicators
    description                           : Monitor your learning progress with at-a-glance indicators, staying motivated and tracking achievements.
    fontawesome_icon_name                 : sync

  - title                                 : Reel-Scrolling Experience
    description                           : Engage with flashcards through vertical scrolling for a dynamic and immersive study experience.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Tap to Flip Cards
    description                           : Interact with flashcards by tapping to reveal answers, promoting active learning and comprehension.
    fontawesome_icon_name                 : star

  - title                                 : Shuffle and Review Modes
    description                           : Customize your study sessions with Shuffle mode to randomize flashcards for memory retention and Review mode to revisit key concepts quickly.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Dark Mode
    description                           : Customize your study environment with a sleek and eye-friendly dark mode, reducing strain during late-night study sessions.
    fontawesome_icon_name                 : link

  - title                                 : User-Friendly Interface
    description                           : The app boasts an intuitive and easy-to-navigate interface, ensuring a seamless and enjoyable user experience.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000" # "#ffffff"

link_color                                : "#48cce4"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

# white background, blue foreground
feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#48cce4"
social_icons_foreground_color             : "#ffffff" # "#666666"
social_icons_background_color             : "#48cce4"

footer_text_color                         : "#48cce4"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
